# Generated by Django 4.1.3 on 2022-12-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('post_author', models.TextField()),
                ('content', models.TextField()),
                ('likes', models.IntegerField()),
                ('post_views', models.IntegerField()),
            ],
        ),
    ]
