# Generated by Django 4.1.3 on 2022-12-19 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TextField()),
                ('password', models.TextField()),
                ('join_date', models.DateTimeField(default=datetime.datetime(2022, 12, 19, 10, 31, 44, 935592, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.RemoveField(
            model_name='posts',
            name='post_author',
        ),
        migrations.AddField(
            model_name='posts',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 10, 31, 44, 935592, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='posts',
            name='post_author_id',
            field=models.IntegerField(default=1),
        ),
    ]
