# Generated by Django 4.1.3 on 2022-12-28 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogservice', '0002_users_remove_posts_post_author_posts_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.TextField(default='28.12.2022'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 28, 16, 1, 39, 910656)),
        ),
        migrations.AlterField(
            model_name='users',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 28, 16, 1, 39, 910656)),
        ),
    ]
