# Generated by Django 4.1.3 on 2023-02-20 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogservice', '0005_remove_likes_like_id_alter_posts_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='preview',
            field=models.ImageField(blank=True, upload_to='previews'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 15, 55, 17, 278509)),
        ),
        migrations.AlterField(
            model_name='users',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 20, 15, 55, 17, 278509)),
        ),
    ]
