# Generated by Django 4.1.3 on 2023-02-22 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogservice', '0007_alter_posts_created_date_alter_posts_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 22, 15, 0, 46, 930523)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_author_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 22, 15, 0, 46, 930523)),
        ),
    ]
